// Map data definitions
export const MAPS = {
    desertOutpost: {
        id: 'desertOutpost',
        name: 'Desert Outpost',
        description: 'Abandoned military outpost in the desert sands',
        thumbnail: 'desert',
        environment: {
            skyColor: 0x87ceeb,
            fogColor: 0xd2b48c,
            fogDensity: 0.015,
            ambientLight: 0.6,
            directionalLight: 1.0,
            groundMaterial: 'sand',
        },
        spawnPoints: [
            { x: -30, y: 0, z: -30, team: 0 },
            { x: 30, y: 0, z: -30, team: 0 },
            { x: -30, y: 0, z: 30, team: 0 },
            { x: 30, y: 0, z: 30, team: 0 },
            { x: 0, y: 0, z: -40, team: 0 },
            { x: 0, y: 0, z: 40, team: 0 },
            { x: -40, y: 0, z: 0, team: 0 },
            { x: 40, y: 0, z: 0, team: 0 },
        ],
        bounds: { x: 60, z: 60 },
    },
    industrialYard: {
        id: 'industrialYard',
        name: 'Industrial Yard',
        description: 'Shipping container maze in an industrial complex',
        thumbnail: 'industrial',
        environment: {
            skyColor: 0x6a7a8a,
            fogColor: 0x5a6a7a,
            fogDensity: 0.02,
            ambientLight: 0.5,
            directionalLight: 0.9,
            groundMaterial: 'concrete',
        },
        spawnPoints: [
            { x: -35, y: 0, z: -35, team: 0 },
            { x: 35, y: 0, z: -35, team: 0 },
            { x: -35, y: 0, z: 35, team: 0 },
            { x: 35, y: 0, z: 35, team: 0 },
            { x: 0, y: 0, z: -45, team: 0 },
            { x: 0, y: 0, z: 45, team: 0 },
            { x: -45, y: 0, z: 0, team: 0 },
            { x: 45, y: 0, z: 0, team: 0 },
        ],
        bounds: { x: 70, z: 70 },
    },
    mountainBase: {
        id: 'mountainBase',
        name: 'Mountain Base',
        description: 'High altitude facility with elevation changes',
        thumbnail: 'mountain',
        environment: {
            skyColor: 0x4a5a7a,
            fogColor: 0x8a9aaa,
            fogDensity: 0.012,
            ambientLight: 0.55,
            directionalLight: 0.95,
            groundMaterial: 'rock',
        },
        spawnPoints: [
            { x: -30, y: 0, z: -30, team: 0 },
            { x: 30, y: 0, z: -30, team: 0 },
            { x: -30, y: 5, z: 30, team: 0 },
            { x: 30, y: 5, z: 30, team: 0 },
            { x: 0, y: 10, z: 0, team: 0 },
            { x: -40, y: 0, z: 0, team: 0 },
            { x: 40, y: 0, z: 0, team: 0 },
            { x: 0, y: 0, z: -40, team: 0 },
        ],
        bounds: { x: 65, z: 65 },
    },
    cityRooftops: {
        id: 'cityRooftops',
        name: 'City Rooftops',
        description: 'Urban rooftop combat with multiple levels',
        thumbnail: 'city',
        environment: {
            skyColor: 0x3a4a5a,
            fogColor: 0x5a6a7a,
            fogDensity: 0.018,
            ambientLight: 0.5,
            directionalLight: 0.85,
            groundMaterial: 'asphalt',
        },
        spawnPoints: [
            { x: -25, y: 10, z: -25, team: 0 },
            { x: 25, y: 10, z: -25, team: 0 },
            { x: -25, y: 5, z: 25, team: 0 },
            { x: 25, y: 5, z: 25, team: 0 },
            { x: 0, y: 15, z: 0, team: 0 },
            { x: -35, y: 0, z: 0, team: 0 },
            { x: 35, y: 0, z: 0, team: 0 },
            { x: 0, y: 0, z: -35, team: 0 },
        ],
        bounds: { x: 55, z: 55 },
    },
};
